from pathlib import Path

ROOT = Path.cwd()

FILES = {
    "requirements.txt": """pandas\nnumpy\nPyYAML\nscikit-learn\njoblib\nmatplotlib\nplotly\nstreamlit\nta\nMetaTrader5\nlightgbm\n""",

    "config.yaml": """app:\n  name: Gold AI Trading Bot\n  mode: paper\n  log_level: INFO\n\nmarket:\n  symbol: XAUUSDm\n  timeframe: M5\n  bars: 1000\n\nrisk:\n  account_balance: 1000\n  risk_per_trade_pct: 1.0\n  fixed_lot: 0.01\n  use_auto_lot: true\n  max_open_positions: 1\n  max_daily_drawdown_pct: 5.0\n\nstrategy:\n  min_confidence: 0.65\n  atr_period: 14\n  swing_lookback: 3\n  fvg_min_points: 20\n\nexecution:\n  dry_run: true\n  deviation: 20\n  magic: 260512\n\nml:\n  model_path: models/lightgbm_model.pkl\n  use_ml_filter: false\n""",

    ".gitignore": """venv/\n__pycache__/\n*.pyc\n.env\nlogs/\ndata/raw/\ndata/cache/\nmodels/*.pkl\nmodels/*.joblib\n""",

    "main.py": """import argparse\nimport yaml\n\nfrom utils.logger import setup_logger\nfrom core.mt5_connector import MT5Connector\nfrom core.feature_engine import FeatureEngine\nfrom strategies.ict_smc_strategy import ICTSMCStrategy\nfrom core.risk_manager import RiskManager\nfrom core.execution_engine import ExecutionEngine\n\n\ndef load_config(path: str) -> dict:\n    with open(path, \"r\", encoding=\"utf-8\") as f:\n        return yaml.safe_load(f)\n\n\ndef main() -> None:\n    parser = argparse.ArgumentParser()\n    parser.add_argument(\"--config\", default=\"config.yaml\")\n    args = parser.parse_args()\n\n    config = load_config(args.config)\n    logger = setup_logger(config[\"app\"].get(\"log_level\", \"INFO\"))\n\n    logger.info(\"Starting Gold AI Trading Bot in %s mode\", config[\"app\"][\"mode\"])\n\n    mt5 = MT5Connector(config, logger)\n    data = mt5.get_rates()\n\n    if data.empty:\n        logger.warning(\"No market data loaded. Check MT5 terminal, symbol, and broker suffix.\")\n        return\n\n    features = FeatureEngine(config).build(data)\n    signal = ICTSMCStrategy(config).generate_signal(features)\n\n    risk = RiskManager(config)\n    order = risk.prepare_order(signal, features.iloc[-1])\n\n    executor = ExecutionEngine(config, logger)\n    result = executor.execute(order)\n\n    logger.info(\"Final result: %s\", result)\n\n\nif __name__ == \"__main__\":\n    main()\n""",

    "utils/logger.py": """import logging\n\n\ndef setup_logger(level: str = \"INFO\") -> logging.Logger:\n    logger = logging.getLogger(\"gold_ai_bot\")\n    logger.setLevel(getattr(logging, level.upper(), logging.INFO))\n\n    if not logger.handlers:\n        handler = logging.StreamHandler()\n        formatter = logging.Formatter(\n            \"%(asctime)s | %(levelname)s | %(name)s | %(message)s\"\n        )\n        handler.setFormatter(formatter)\n        logger.addHandler(handler)\n\n    return logger\n""",

    "core/mt5_connector.py": """from __future__ import annotations\n\nimport pandas as pd\n\ntry:\n    import MetaTrader5 as mt5\nexcept Exception:  # pragma: no cover\n    mt5 = None\n\n\nTIMEFRAME_MAP = {\n    \"M1\": 1,\n    \"M5\": 5,\n    \"M15\": 15,\n    \"M30\": 30,\n    \"H1\": 16385,\n    \"H4\": 16388,\n    \"D1\": 16408,\n}\n\n\nclass MT5Connector:\n    def __init__(self, config: dict, logger):\n        self.config = config\n        self.logger = logger\n        self.symbol = config[\"market\"][\"symbol\"]\n        self.timeframe = config[\"market\"].get(\"timeframe\", \"M5\")\n        self.bars = int(config[\"market\"].get(\"bars\", 1000))\n\n    def get_rates(self) -> pd.DataFrame:\n        if mt5 is None:\n            self.logger.warning(\"MetaTrader5 package not installed. Returning empty dataframe.\")\n            return pd.DataFrame()\n\n        if not mt5.initialize():\n            self.logger.error(\"MT5 initialize failed: %s\", mt5.last_error())\n            return pd.DataFrame()\n\n        tf = TIMEFRAME_MAP.get(self.timeframe, TIMEFRAME_MAP[\"M5\"])\n        rates = mt5.copy_rates_from_pos(self.symbol, tf, 0, self.bars)\n\n        if rates is None:\n            self.logger.error(\"MT5 data request failed: %s\", mt5.last_error())\n            return pd.DataFrame()\n\n        df = pd.DataFrame(rates)\n        if df.empty:\n            return df\n\n        df[\"time\"] = pd.to_datetime(df[\"time\"], unit=\"s\")\n        return df\n""",

    "core/feature_engine.py": """from __future__ import annotations\n\nimport pandas as pd\nimport numpy as np\n\nfrom strategies.fvg_detector import detect_fvg\nfrom strategies.market_structure import detect_swings, detect_bos\nfrom strategies.liquidity_sweep import detect_liquidity_sweep\n\n\nclass FeatureEngine:\n    def __init__(self, config: dict):\n        self.config = config\n\n    def build(self, df: pd.DataFrame) -> pd.DataFrame:\n        out = df.copy()\n\n        out[\"return\"] = out[\"close\"].pct_change()\n        out[\"range\"] = out[\"high\"] - out[\"low\"]\n        out[\"body\"] = (out[\"close\"] - out[\"open\"]).abs()\n        out[\"direction\"] = np.where(out[\"close\"] > out[\"open\"], 1, -1)\n        out[\"atr\"] = self._atr(out, self.config[\"strategy\"].get(\"atr_period\", 14))\n\n        out = detect_fvg(out, self.config)\n        out = detect_swings(out, self.config)\n        out = detect_bos(out)\n        out = detect_liquidity_sweep(out)\n\n        return out.dropna().reset_index(drop=True)\n\n    @staticmethod\n    def _atr(df: pd.DataFrame, period: int) -> pd.Series:\n        high_low = df[\"high\"] - df[\"low\"]\n        high_close = (df[\"high\"] - df[\"close\"].shift()).abs()\n        low_close = (df[\"low\"] - df[\"close\"].shift()).abs()\n        tr = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)\n        return tr.rolling(period).mean()\n""",

    "strategies/fvg_detector.py": """from __future__ import annotations\n\nimport pandas as pd\n\n\ndef detect_fvg(df: pd.DataFrame, config: dict) -> pd.DataFrame:\n    out = df.copy()\n    out[\"bullish_fvg\"] = False\n    out[\"bearish_fvg\"] = False\n    out[\"fvg_low\"] = None\n    out[\"fvg_high\"] = None\n\n    min_points = float(config[\"strategy\"].get(\"fvg_min_points\", 0))\n\n    for i in range(2, len(out)):\n        a = out.iloc[i - 2]\n        c = out.iloc[i]\n\n        bullish_gap = c[\"low\"] - a[\"high\"]\n        bearish_gap = a[\"low\"] - c[\"high\"]\n\n        if bullish_gap > min_points:\n            out.at[out.index[i], \"bullish_fvg\"] = True\n            out.at[out.index[i], \"fvg_low\"] = a[\"high\"]\n            out.at[out.index[i], \"fvg_high\"] = c[\"low\"]\n\n        if bearish_gap > min_points:\n            out.at[out.index[i], \"bearish_fvg\"] = True\n            out.at[out.index[i], \"fvg_low\"] = c[\"high\"]\n            out.at[out.index[i], \"fvg_high\"] = a[\"low\"]\n\n    return out\n""",

    "strategies/market_structure.py": """from __future__ import annotations\n\nimport pandas as pd\n\n\ndef detect_swings(df: pd.DataFrame, config: dict) -> pd.DataFrame:\n    out = df.copy()\n    lookback = int(config[\"strategy\"].get(\"swing_lookback\", 3))\n    out[\"swing_high\"] = False\n    out[\"swing_low\"] = False\n\n    for i in range(lookback, len(out) - lookback):\n        window = out.iloc[i - lookback:i + lookback + 1]\n        if out.iloc[i][\"high\"] == window[\"high\"].max():\n            out.at[out.index[i], \"swing_high\"] = True\n        if out.iloc[i][\"low\"] == window[\"low\"].min():\n            out.at[out.index[i], \"swing_low\"] = True\n\n    return out\n\n\ndef detect_bos(df: pd.DataFrame) -> pd.DataFrame:\n    out = df.copy()\n    out[\"bullish_bos\"] = False\n    out[\"bearish_bos\"] = False\n\n    last_swing_high = None\n    last_swing_low = None\n\n    for i, row in out.iterrows():\n        if row.get(\"swing_high\"):\n            last_swing_high = row[\"high\"]\n        if row.get(\"swing_low\"):\n            last_swing_low = row[\"low\"]\n\n        if last_swing_high is not None and row[\"close\"] > last_swing_high:\n            out.at[i, \"bullish_bos\"] = True\n        if last_swing_low is not None and row[\"close\"] < last_swing_low:\n            out.at[i, \"bearish_bos\"] = True\n\n    return out\n""",

    "strategies/liquidity_sweep.py": """from __future__ import annotations\n\nimport pandas as pd\n\n\ndef detect_liquidity_sweep(df: pd.DataFrame) -> pd.DataFrame:\n    out = df.copy()\n    out[\"bullish_sweep\"] = False\n    out[\"bearish_sweep\"] = False\n\n    prev_high = out[\"high\"].shift(1)\n    prev_low = out[\"low\"].shift(1)\n\n    out[\"bearish_sweep\"] = (out[\"high\"] > prev_high) & (out[\"close\"] < prev_high)\n    out[\"bullish_sweep\"] = (out[\"low\"] < prev_low) & (out[\"close\"] > prev_low)\n\n    return out\n""",

    "strategies/ict_smc_strategy.py": """from __future__ import annotations\n\nimport pandas as pd\n\n\nclass ICTSMCStrategy:\n    def __init__(self, config: dict):\n        self.config = config\n        self.min_confidence = float(config[\"strategy\"].get(\"min_confidence\", 0.65))\n\n    def generate_signal(self, df: pd.DataFrame) -> dict:\n        row = df.iloc[-1]\n\n        buy_score = 0.0\n        sell_score = 0.0\n        reasons = []\n\n        if row.get(\"bullish_fvg\"):\n            buy_score += 0.3\n            reasons.append(\"bullish_fvg\")\n        if row.get(\"bullish_bos\"):\n            buy_score += 0.3\n            reasons.append(\"bullish_bos\")\n        if row.get(\"bullish_sweep\"):\n            buy_score += 0.2\n            reasons.append(\"bullish_liquidity_sweep\")\n\n        if row.get(\"bearish_fvg\"):\n            sell_score += 0.3\n            reasons.append(\"bearish_fvg\")\n        if row.get(\"bearish_bos\"):\n            sell_score += 0.3\n            reasons.append(\"bearish_bos\")\n        if row.get(\"bearish_sweep\"):\n            sell_score += 0.2\n            reasons.append(\"bearish_liquidity_sweep\")\n\n        if buy_score >= self.min_confidence and buy_score > sell_score:\n            return {\"side\": \"BUY\", \"confidence\": buy_score, \"reasons\": reasons}\n\n        if sell_score >= self.min_confidence and sell_score > buy_score:\n            return {\"side\": \"SELL\", \"confidence\": sell_score, \"reasons\": reasons}\n\n        return {\"side\": \"NONE\", \"confidence\": max(buy_score, sell_score), \"reasons\": reasons}\n""",

    "core/risk_manager.py": """from __future__ import annotations\n\n\nclass RiskManager:\n    def __init__(self, config: dict):\n        self.config = config\n\n    def prepare_order(self, signal: dict, latest_row) -> dict:\n        if signal[\"side\"] == \"NONE\":\n            return {\"action\": \"NO_TRADE\", \"reason\": \"No valid signal\", \"signal\": signal}\n\n        atr = float(latest_row.get(\"atr\", 0))\n        price = float(latest_row.get(\"close\"))\n        lot = self._calculate_lot(atr)\n\n        if signal[\"side\"] == \"BUY\":\n            sl = price - atr * 1.5\n            tp = price + atr * 3.0\n        else:\n            sl = price + atr * 1.5\n            tp = price - atr * 3.0\n\n        return {\n            \"action\": \"OPEN\",\n            \"side\": signal[\"side\"],\n            \"symbol\": self.config[\"market\"][\"symbol\"],\n            \"lot\": lot,\n            \"price\": price,\n            \"sl\": round(sl, 3),\n            \"tp\": round(tp, 3),\n            \"confidence\": signal[\"confidence\"],\n            \"reasons\": signal[\"reasons\"],\n        }\n\n    def _calculate_lot(self, atr: float) -> float:\n        risk_cfg = self.config[\"risk\"]\n        if not risk_cfg.get(\"use_auto_lot\", True):\n            return float(risk_cfg.get(\"fixed_lot\", 0.01))\n\n        balance = float(risk_cfg.get(\"account_balance\", 1000))\n        risk_pct = float(risk_cfg.get(\"risk_per_trade_pct\", 1.0)) / 100\n\n        risk_amount = balance * risk_pct\n        rough_lot = risk_amount / max(atr * 100, 1)\n        return max(round(rough_lot, 2), 0.01)\n""",

    "core/execution_engine.py": """from __future__ import annotations\n\n\nclass ExecutionEngine:\n    def __init__(self, config: dict, logger):\n        self.config = config\n        self.logger = logger\n        self.dry_run = bool(config[\"execution\"].get(\"dry_run\", True))\n\n    def execute(self, order: dict) -> dict:\n        if order.get(\"action\") == \"NO_TRADE\":\n            return {\"status\": \"SKIPPED\", \"order\": order}\n\n        if self.dry_run:\n            self.logger.info(\"DRY RUN order: %s\", order)\n            return {\"status\": \"DRY_RUN\", \"order\": order}\n\n        return {\n            \"status\": \"BLOCKED\",\n            \"reason\": \"Real execution is intentionally not implemented in v1 scaffold.\",\n            \"order\": order,\n        }\n""",

    "ml/regime_detector.py": """from __future__ import annotations\n\nimport pandas as pd\n\n\ndef detect_regime(df: pd.DataFrame) -> str:\n    if len(df) < 50:\n        return \"UNKNOWN\"\n\n    recent_vol = df[\"return\"].tail(20).std()\n    base_vol = df[\"return\"].tail(100).std()\n\n    if recent_vol > base_vol * 1.5:\n        return \"HIGH_VOL\"\n    if recent_vol < base_vol * 0.7:\n        return \"LOW_VOL\"\n    return \"NORMAL\"\n""",

    "ml/train_lightgbm.py": """from __future__ import annotations\n\nfrom pathlib import Path\nimport joblib\nimport pandas as pd\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import classification_report\n\ntry:\n    from lightgbm import LGBMClassifier\nexcept Exception:\n    LGBMClassifier = None\n\n\nFEATURES = [\"return\", \"range\", \"body\", \"atr\"]\n\n\ndef train(csv_path: str, model_path: str = \"models/lightgbm_model.pkl\") -> None:\n    if LGBMClassifier is None:\n        raise RuntimeError(\"lightgbm is not installed\")\n\n    df = pd.read_csv(csv_path)\n    df[\"future_return\"] = df[\"close\"].shift(-5) / df[\"close\"] - 1\n    df[\"target\"] = (df[\"future_return\"] > 0).astype(int)\n    df = df.dropna()\n\n    x = df[FEATURES]\n    y = df[\"target\"]\n\n    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, shuffle=False)\n\n    model = LGBMClassifier(n_estimators=300, learning_rate=0.03, max_depth=4)\n    model.fit(x_train, y_train)\n\n    preds = model.predict(x_test)\n    print(classification_report(y_test, preds))\n\n    Path(model_path).parent.mkdir(parents=True, exist_ok=True)\n    joblib.dump(model, model_path)\n\n\nif __name__ == \"__main__\":\n    train(\"data/history.csv\")\n""",

    "backtest/backtester.py": """from __future__ import annotations\n\nimport pandas as pd\n\n\nclass Backtester:\n    def __init__(self, initial_balance: float = 1000):\n        self.initial_balance = initial_balance\n\n    def run(self, df: pd.DataFrame) -> dict:\n        return {\n            \"initial_balance\": self.initial_balance,\n            \"trades\": 0,\n            \"net_profit\": 0.0,\n            \"max_drawdown\": 0.0,\n            \"note\": \"Backtest engine placeholder. Next step: add trade simulation loop.\",\n        }\n""",

    "dashboard/app.py": """import streamlit as st\n\nst.set_page_config(page_title=\"Gold AI Bot Dashboard\", layout=\"wide\")\nst.title(\"Gold AI Trading Bot Dashboard\")\nst.warning(\"Dashboard v1: research and monitoring only.\")\nst.write(\"Next: add equity curve, signals, open risk, and model confidence.\")\n""",
}

DIRS = [
    "core",
    "strategies",
    "ml",
    "backtest",
    "dashboard",
    "utils",
    "data/raw",
    "data/cache",
    "models",
    "logs",
]

for directory in DIRS:
    (ROOT / directory).mkdir(parents=True, exist_ok=True)

for path, content in FILES.items():
    file_path = ROOT / path
    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_text(content, encoding="utf-8")

for package in ["core", "strategies", "ml", "backtest", "utils"]:
    init_file = ROOT / package / "__init__.py"
    init_file.write_text("", encoding="utf-8")

print("Project scaffold created successfully.")
print("Next commands:")
print("  python -m venv venv")
print("  venv\\Scripts\\activate")
print("  pip install -r requirements.txt")
print("  python main.py --config config.yaml")
